### ISSUE TITLE
Prepare structure for wordpress

### ISSUE THREAD

**Issue by manuelver** [prefapp/charts#118]
### Motivation
Prepare environment to migrate wordpress website from prefapp to k8s. For the implementation you must use the infra, charts and status of github prefapp.

It must take into account the constraints of the wordpress app and best practices in a cloud environment. 

### Acceptance criteria
- [x] Template creation for pvc.yaml
- [x] Provisioning via terraform:
  - [x] EFS
    - [x] Add access point in EFS
  - [x] Create policy and IAM role to connect pv with efs. Guide:  https://aws.amazon.com/es/blogs/storage/persistent-storage-for-kubernetes/
  - [x] RDS
    - [x] Add security group for mysql
  - [x] Add domain for testing
  - [x] Add repository in ECR
- [x] Migration of the database
- [x] Add aws-efs-csi-driver in state
- [x] Prepare to update php 7.2 > 8.2
  - [x] Upgrade elementor pro and smart slider plugins
  - [x] Replace wp-rocket plugin for cache
  - [x] Fix errors in company page and ticket
- [x] Use the dockerhub image: https://hub.docker.com/_/wordpress
  - [x] Disable automatic wordpress updates. Control from image
- [x] Check connectivity
- [x] Testing of pod restarts.
- [x] Editing tests using wordpress. 
- [ ] Acceptance by responsible persons

**Comment by manuelver** [comment]
[PR](https://github.com/prefapp/infra/pull/12) provision EFS in terraform

**Comment by manuelver** [comment]
[PR](https://github.com/prefapp/state/pull/132)  Create wordpress status in state repo

**Comment by alambike** [comment]
You mean state, right?

**Comment by manuelver** [comment]
> You mean state, right?

right

**Comment by manuelver** [comment]
- [PR Update RDS security group to add mysql port](https://github.com/prefapp/infra/pull/16)
- [PR Add domain for prefapp web testing](https://github.com/prefapp/infra/pull/15)
- [PR Add services/web-prefapp repository in ECR](https://github.com/prefapp/infra/pull/17)

**Comment by manuelver** [comment]
Add EFS Access Point
[PR](https://github.com/prefapp/infra/pull/23) in infra
[PR](https://github.com/prefapp/state/pull/176) in state

**Comment by manuelver** [comment]
[PR](https://github.com/prefapp/state/pull/177)  Set wordpress image version

**Comment by manuelver** [comment]
Capture of the result in dev

![image](https://github.com/prefapp/charts/assets/86802064/919a666f-bf3b-4d2e-a4a7-03fd34b2f025)
