### ISSUE TITLE
Create a generic helm chart with proxified power

### ISSUE THREAD

**Issue by gustavoborragan** [prefapp/charts#75]
## Motivation

We need to create a generic helm chart with proxy power, that is, the application is served through a proxy and not directly. This will be done via an init container with an nginx proxy attached to the application container.

This will allow additional rules to be extended on nginx regardless of the chosen load balancer.

## Criteria
- [x] Chart
  - [x] Template
    - [x] configmap
    - [x] secret
    - [x] deployment
    - [x] ingress
    - [x] service
  - [x] Repo
    - [x] Chart
    - [x] Documentation
      - [x] Logo 
      - [x] Purpose
      - [x] To install
      - [x] Requirements
        - [x] None
      - [x] Values
      - [x] License
    - [x] Worfflow release to artifacthub
- [x]  Image
  - [x] Dockerfile
  - [x] docker-compose for testing
  - [x] script perl
  - [x] Bootscript
  - [x] Build & push script
  - [x] Documentation

**Comment by alambike** [comment]
Depends on https://github.com/prefapp/charts/issues/81

**Comment by gustavoborragan** [comment]
[Link generic proxified chart](https://github.com/prefapp/charts/tree/master/charts/aws-web-service-proxified)
